name: CreditConomy
description: Credit based Economy plugin.
main: com.domsplace.CreditConomy.CreditConomyPlugin
authors: [Dominic, Jordan]
website: http://domsplace.com/
version: '1.01'
softdepend: [Vault]
commands:
   balance:
      description: Returns your balance.
      aliases: [getbalance, getcash, cash, credits, getcredits]
      usage: /<command> (player)
      permission: CreditConomy.balance
   addcredits:
      description: Adds credits to a players balance.
      aliases: [addcreds]
      usage: /<command> [player] [amount]
      permission: CreditConomy.addcredits
   pay:
      description: Send money to someone.
      aliases: [sendmoney, sendcredits]
      usage: /<command> [player] [amount]
      permission: CreditConomy.pay
permissions:
   CreditConomy.*:
     description: Gives access to all CreditConomy permissions.
     children:
       CreditConomy.balance.*: true
       CreditConomy.addcredits: true
       CreditConomy.pay: true
   CreditConomy.balance:
     description: Allows access to the balance command.
   CreditConomy.balance.others:
     description: Allows access to get the balance of another player.
   CreditConomy.balance.*:
     description: Allows access to all the balance permissions.
     children:
       CreditConomy.balance: true
       CreditConomy.balance.others: true
   CreditConomy.addcredits:
     description: Allows access to the addcredits command.
   CreditConomy.pay:
     description: Allows access to the pay command.